ready for review

diff --git a/.github/workflows/ready_for_review.yml b/.github/workflows/ready_for_review.yml
--- a/.github/workflows/ready_for_review.yml
+++ b/.github/workflows/ready_for_review.yml
@@ -1,7 +1,7 @@
 name: Pull Request Ready for Review
 on:
   pull_request:
-     types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, review_requested, review_request_removed, labeled, unlabeled]
+     types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, review_requested, review_request_removed, labeled]
   workflow_run:
     workflows: ["Code Checks", "Check CODEOWNERS Entries", "Audit Service Tags", "CodeQL"]
     types: [completed]
@@ -39,8 +39,14 @@ jobs:
             echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
             echo "pr_draft=${{ github.event.pull_request.draft }}" >> $GITHUB_OUTPUT
             echo "pr_labels=$(echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | jq -c '.')" >> $GITHUB_OUTPUT
-            echo "pr_requested_teams=$(echo '${{ toJSON(github.event.pull_request.requested_teams.*.name) }}' | jq -c '.')" >> $GITHUB_OUTPUT
             echo "pr_branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
+
+            if ${{ github.event.pull_request.draft }}; then
+              echo "pr_requested_teams=[]" >> $GITHUB_OUTPUT
+            else
+              echo "pr_requested_teams=$(echo '${{ toJSON(github.event.pull_request.requested_teams.*.name) }}' | jq -c '.')" >> $GITHUB_OUTPUT
+            fi
+
           elif ${{ github.event_name == 'workflow_run' }}; then
             if ${{ github.event.workflow_run.event == 'push' }}; then
               HEAD_BRANCH="${{ github.event.workflow_run.head_branch }}"
@@ -59,9 +65,18 @@ jobs:
               }')
 
               # Extract and store individual fields
-              echo "pr_draft=$(echo "$PR_INFO" | jq -r '.draft')" >> $GITHUB_OUTPUT
-              echo "pr_labels=$(echo "$PR_INFO" | jq -c '.labels')" >> $GITHUB_OUTPUT
-              echo "pr_requested_teams=$(echo "$PR_INFO" | jq -c '.requested_teams')" >> $GITHUB_OUTPUT
+              PR_DRAFT=$(echo "$PR_INFO" | jq -r '.draft')
+              PR_LABELS=$(echo "$PR_INFO" | jq -c '.labels')
+
+              echo "pr_draft=$PR_DRAFT" >> $GITHUB_OUTPUT
+              echo "pr_labels=$PR_LABELS" >> $GITHUB_OUTPUT
+
+              if [[ "$PR_DRAFT" == "true" ]]; then
+                echo "pr_requested_teams=[]" >> $GITHUB_OUTPUT
+              else
+                PR_REQUESTED_TEAMS=$(echo "$PR_INFO" | jq -c '.requested_teams')
+                echo "pr_requested_teams=$PR_REQUESTED_TEAMS" >> $GITHUB_OUTPUT
+              fi
             else
               echo "Workflow run has no associated pull requests. Labeling not performed."
               exit 0
@@ -72,9 +87,31 @@ jobs:
             exit 1
           fi
 
+      - name: Remove require-backend-approval label
+        uses: actions-ecosystem/action-remove-labels@v1
+        if: steps.get_pr_data.outputs.pr_draft == 'true'
+        with:
+          number: ${{ env.pr_number }}
+          labels: require-backend-approval
+
+      - name: Remove ready-for-backend-review label
+        if: steps.get_pr_data.outputs.pr_draft == 'true'
+        uses: actions-ecosystem/action-remove-labels@v1
+        with:
+          number: ${{ needs.get-pr-data.outputs.pr_number }}
+          labels: ready-for-backend-review
+
+      - name: Remove ready-for-review label
+        if: steps.get_pr_data.outputs.pr_draft == 'true'
+        uses: actions-ecosystem/action-remove-labels@v1
+        with:
+          number: ${{ env.pr_number }}
+          labels: ready-for-review
+
   check-workflow-status:
     name: Check Workflow Statuses
     needs: [get-pr-data]
+    if: needs.get-pr-data.outputs.pr_draft == 'false'
     runs-on: ubuntu-latest
     permissions: write-all
     env:
@@ -82,11 +119,13 @@ jobs:
       pr_branch: ${{ needs.get-pr-data.outputs.pr_branch }}
     outputs:
       failures_detected: ${{ steps.check_workflow_status.outputs.failures_detected }}
+      all_workflows_failing: ${{ steps.check_workflow_status.outputs.all_workflows_failing }}
     steps:
       - name: Check if workflows have completed successfully
         id: check_workflow_status
         run: |
           failures=false
+          all_workflows_failing=true
           GITHUB_REPOSITORY="department-of-veterans-affairs/vets-api"
           WORKFLOWS=("Code Checks" "Check CODEOWNERS Entries" "Audit Service Tags" "CodeQL")
 
@@ -98,6 +137,7 @@ jobs:
             if [ -n "$IN_PROGRESS" ]; then
               echo "$WORKFLOW is still in progress."
               failures=true
+              all_workflows_failing=false
             else
               # Check if the latest completed run was successful
               SUCCESSFUL=$(gh run list --repo "$GITHUB_REPOSITORY" --workflow="$WORKFLOW" --status=completed --json headBranch,event,conclusion -q \
@@ -108,11 +148,13 @@ jobs:
                 # break
               else
                 echo "$WORKFLOW completed successfully."
+                all_workflows_failing=false
               fi
             fi
           done
 
           echo "failures_detected=$failures" >> "$GITHUB_OUTPUT"
+          echo "all_workflows_failing=$all_workflows_failing" >> "$GITHUB_OUTPUT"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -133,34 +175,70 @@ jobs:
   check-backend-requirement:
     name: Check Backend Requirement
     needs: [get-pr-data, check-workflow-status]
+    if: needs.get-pr-data.outputs.pr_draft == 'false'
     runs-on: ubuntu-latest
     permissions: write-all
     env:
+      all_workflows_failing:  ${{ needs.check-workflow-status.outputs.all_workflows_failing }}
       failures_detected:  ${{ needs.check-workflow-status.outputs.failures_detected }}
       pr_number: ${{ needs.get-pr-data.outputs.pr_number }}
       pr_labels: ${{ needs.get-pr-data.outputs.pr_labels }}
       pr_requested_teams: ${{ needs.get-pr-data.outputs.pr_requested_teams }}
     outputs:
+      exception_groups: ${{ steps.check_exception_groups.outputs.exception_groups }}
       backend_approval_required: ${{ steps.check_backend_requirement.outputs.backend_approval_required }}
     steps:
+      - name: Check for Excempt Teams
+        id: check_exception_groups
+        run: |
+          exception_groups=false
+          TEAMS=$(echo '${{ env.pr_requested_teams }}' | jq -r '.[]')
+          for TEAM in $TEAMS; do
+            case "$TEAM" in
+              mobile|lighthouse|identity)
+                echo "Found team: $TEAM"
+                exception_groups=true
+                break
+                ;;
+            esac
+          done
+          echo "exception_groups=$exception_groups" >> $GITHUB_OUTPUT
+
       - name: Check Backend Requirement
         id: check_backend_requirement
-        if: |
-          ${{ contains(fromJSON(env.pr_requested_teams), 'backend-review-group') }} ||
-          ${{ contains(fromJSON(env.pr_labels), 'require-backend-approval') }}
         run: |
-          echo "backend_approval_required=true" >> $GITHUB_OUTPUT
+          echo "backend_approval_required=false" >> $GITHUB_OUTPUT
+
+          if [[ "${{ steps.check_exception_groups.outputs.exception_groups }}" == "false" ]]; then
+            echo "Excemption Groups were not found"
+            echo "backend_approval_required=true" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+
+          echo "${{ env.pr_requested_teams }}" | jq -e '. | index("backend-review-group")' > /dev/null
+          if [[ $? -eq 0 ]]; then
+            echo "backend-review-group found in requested teams"
+            echo "backend_approval_required=true" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+
+          echo "${{ env.pr_labels }}" | jq -e '. | index("require-backend-approval")' > /dev/null
+          if [[ $? -eq 0 ]]; then
+            echo "require-backend-approval found in labels"
+            echo "backend_approval_required=true" >> $GITHUB_OUTPUT
+            exit 0
+          fi
 
       - name: Add require-backend-approval label
         uses: actions-ecosystem/action-add-labels@v1
-        if: steps.check_backend_requirement.outputs.backend_approval_required == 'true'  && needs.check-workflow-status.outputs.failures_detected == 'false'
+        if: steps.check_backend_requirement.outputs.backend_approval_required == 'true'
         with:
           number: ${{ env.pr_number }}
           labels: require-backend-approval
 
       - name: Remove require-backend-approval label
         uses: actions-ecosystem/action-remove-labels@v1
-        if: steps.check_backend_requirement.outputs.backend_approval_required == 'false' && needs.check-workflow-status.outputs.failures_detected == 'false'
+        if: steps.check_backend_requirement.outputs.backend_approval_required == 'false'
         with:
           number: ${{ env.pr_number }}
           labels: require-backend-approval
@@ -168,6 +246,7 @@ jobs:
   fetch-pr-reviews:
     name: Fetch Pull Request Reviews
     needs: [get-pr-data, check-workflow-status, check-backend-requirement]
+    if: needs.get-pr-data.outputs.pr_draft == 'false'
     runs-on: ubuntu-latest
     permissions: write-all
     env:
@@ -241,13 +320,19 @@ jobs:
             team_approval_status=confirmed
           fi
 
-          BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
-          echo "Backend Approvals: $BE_APPROVALS"
-          if [ -z "$BE_APPROVALS" ]; then
-            echo "BE APPROVAL REQUIRED"
-            approval_status=required
+
+          if [[ "${{ needs.check-backend-requirement.outputs.backend_approval_required }}" == "true" ]]; then
+            BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
+            echo "Backend Approvals: $BE_APPROVALS"
+            if [ -z "$BE_APPROVALS" ]; then
+              echo "BE APPROVAL REQUIRED"
+              approval_status=required
+            else
+              echo "BE APPROVAL CONFIRMED"
+              approval_status=confirmed
+            fi
           else
-            echo "BE APPROVAL CONFIRMED"
+            echo "Backend Approval is not required."
             approval_status=confirmed
           fi
 
@@ -256,25 +341,6 @@ jobs:
           echo "approval_status=$approval_status" >> "$GITHUB_OUTPUT"
         env:
           GITHUB_TOKEN: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
-
-      - name: Remove ready-for-backend-review label
-        if: needs.get-pr-data.outputs.pr_draft == 'true' || needs.check-workflow-status.outputs.failures_detected == 'true'
-        uses: actions-ecosystem/action-remove-labels@v1
-        with:
-          number: ${{ needs.get-pr-data.outputs.pr_number }}
-          labels: ready-for-backend-review
-
-      - name: Remove ready-for-review label
-        if: needs.get-pr-data.outputs.pr_draft == 'true' || needs.check-workflow-status.outputs.failures_detected == 'true'
-        uses: actions-ecosystem/action-remove-labels@v1
-        with:
-          number: ${{ env.pr_number }}
-          labels: ready-for-review
-
-
-      - name: Fail if draft
-        if: needs.get-pr-data.outputs.pr_draft == 'true'
-        run: exit 1
 
       # The ready-for-review label will be added when pull request has not been reviewed
       - name: Add ready-for-review label
