test

diff --git a/.github/workflows/ready_for_review.yml b/.github/workflows/ready_for_review.yml
--- a/.github/workflows/ready_for_review.yml
+++ b/.github/workflows/ready_for_review.yml
@@ -228,6 +228,7 @@ jobs:
           backend_approval_required=true
           exempt_team=false
           exempt_author=false
+          review_complete=false
           PR_REQUESTED_TEAMS="${{ env.pr_requested_teams }}"
           PR_AUTHOR=${{ env.pr_author }}
           PR_REQUESTED_TEAMS_JSON=$(echo "$PR_REQUESTED_TEAMS" | sed 's/\[/["/' | sed 's/\]/"]/' | sed 's/,/","/g')
@@ -247,6 +248,19 @@ jobs:
           BACKEND_REVIEWERS=$(echo "$BACKEND_REVIEWERS" | tr '\n' '|' | sed 's/|$//')
           echo "Backend reviewers regex: $BACKEND_REVIEWERS"
 
+          if [ -z "$PR_REQUESTED_TEAMS_JSON" ] || [ "$PR_REQUESTED_TEAMS_JSON" = "[]" ]; then
+            # Check PR Labels
+            PR_LABELS="${pr_labels}"
+            echo "$PR_LABELS" | jq -r '.[]' | while read -r LABEL; do
+              echo "Fetching label: $LABEL"
+              if [[ "$LABEL" == "require-backend-approval" ]]; then
+                echo "$LABEL exists"
+                exempt_team=false
+                backend_approval_required=true
+              fi
+            done
+          fi
+
           # Get PR author
           PR_AUTHOR=${{ env.pr_author }}
           if echo "$PR_AUTHOR" | grep -qiE "^($BACKEND_REVIEWERS)$"; then
@@ -256,61 +270,30 @@ jobs:
             echo "PR author '$PR_AUTHOR' is NOT a backend-review-group member."
           fi
 
-          APPROVED=$(gh api /repos/${{ github.repository }}/pulls/${pr_number}/reviews --jq '
-            [ .[]
-            | select(.state == "APPROVED")
-            ]
-            | sort_by(.submitted_at)
-            | reverse
-            | unique_by(.user.login)
-            | .[].user.login
-          ' || true)
+          readarray -t APPROVED < <(
+            gh api /repos/${{ github.repository }}/pulls/${pr_number}/reviews --jq '
+              [ .[]
+              | select(.state == "APPROVED")
+              ]
+              | sort_by(.submitted_at)
+              | reverse
+              | unique_by(.user.login)
+              | .[].user.login
+            ' || true
+          )
 
-          for TEAM in "${EXEMPT_TEAMS[@]}"; do
-            echo "Non BE Requested Team: $TEAM"
-            if [[ "$author_is_backend" == "false" ]]; then
-              membership_state=$(gh api -X GET \
-                "orgs/department-of-veterans-affairs/teams/${TEAM}/memberships/$PR_AUTHOR" \
-                --jq '.state' 2>/dev/null || echo "")
-              if [[ "$membership_state" == "active" ]]; then
-                echo "PR author '$PR_AUTHOR' is a member of exempt team '$TEAM'."
-                exempt_team=true
-                backend_approval_required=false
-                break
-              fi
-            fi
-            if echo "$PR_REQUESTED_TEAMS_JSON" | jq -e ". | index(\"$TEAM\")" > /dev/null; then
-              echo "Excemption Teams were found: $TEAM"
-              exempt_team=true
-              backend_approval_required=false
-              break
-            fi
-          done
-
-          if [[ -n "$APPROVED" ]]; then
-            echo "Approved by: $APPROVED"
-            TEAM_APPROVALS=$(echo "$APPROVED" | grep -viE "^($BACKEND_REVIEWERS)$" || true)
-            BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
-
-            echo "Team Approvals: $TEAM_APPROVALS"
-
-            if [ -z "$TEAM_APPROVALS" ]; then
-              echo "TEAM APPROVAL REQUIRED"
-            else
-              echo "TEAM APPROVAL CONFIRMED"
-              team_approval_status=confirmed
-            fi
-
-            if [ -z "$BE_APPROVALS" ]; then
-              echo "PR Reviewer '$APPROVED' is NOT a backend-review-group member."
+          echo "Approvers: ${APPROVED[@]}"
+          for approve in "${APPROVED[@]}"; do
+            echo "Checking approver: $approve"
+            if echo "$approve" | grep -viE "^($BACKEND_REVIEWERS)$"; then
+              echo "PR Reviewer '$approve' is NOT a backend-review-group member."
               for TEAM in "${EXEMPT_TEAMS[@]}"; do
-                echo "Fetching members of team: $TEAM"
                 membership_state=$(gh api -X GET \
-                  "orgs/department-of-veterans-affairs/teams/${TEAM}/memberships/$APPROVED" \
+                  "orgs/department-of-veterans-affairs/teams/${TEAM}/memberships/$approve" \
                   --jq '.state' 2>/dev/null || echo "")
-
                 if [[ "$membership_state" == "active" ]]; then
-                  echo "Reviewer is a member of an exempt team"
+                  echo "$approve is an active member of $TEAM"
+                  review_complete=true
                   exempt_team=true
                   backend_approval_required=false
                   approval_status=confirmed
@@ -319,19 +302,56 @@ jobs:
                 fi
               done
             fi
+          done
 
-            if [[ "${exempt_team}" == "false" ]]; then
-              echo "Backend Approvals: $BE_APPROVALS"
-              if [ -z "$BE_APPROVALS" ]; then
-                echo "BE APPROVAL REQUIRED"
-              else
-                echo "BE APPROVAL CONFIRMED"
-                approval_status=confirmed
-                backend_approval_required=false
+          if [[ "${review_complete}" == "false" ]]; then
+            for TEAM in "${EXEMPT_TEAMS[@]}"; do
+              echo "Non BE Requested Team: $TEAM"
+              if [[ "$author_is_backend" == "false" ]]; then
+                membership_state=$(gh api -X GET \
+                  "orgs/department-of-veterans-affairs/teams/${TEAM}/memberships/$PR_AUTHOR" \
+                  --jq '.state' 2>/dev/null || echo "")
+                if [[ "$membership_state" == "active" ]]; then
+                  echo "PR author '$PR_AUTHOR' is a member of exempt team '$TEAM'."
+                  exempt_team=true
+                  backend_approval_required=false
+                  break
+                fi
               fi
+              if echo "$PR_REQUESTED_TEAMS_JSON" | jq -e ". | index(\"$TEAM\")" > /dev/null; then
+                echo "Excemption Teams were found: $TEAM"
+                exempt_team=true
+                backend_approval_required=false
+                break
+              fi
+            done
+
+            if [[ -n "$APPROVED" ]]; then
+              echo "Approved by: $APPROVED"
+              TEAM_APPROVALS=$(echo "$APPROVED" | grep -viE "^($BACKEND_REVIEWERS)$" || true)
+              BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
+
+              echo "Team Approvals: $TEAM_APPROVALS"
+              if [ -z "$TEAM_APPROVALS" ]; then
+                echo "TEAM APPROVAL REQUIRED"
+              else
+                echo "TEAM APPROVAL CONFIRMED"
+                team_approval_status=confirmed
+              fi
+
+              if [[ "${exempt_team}" == "false" ]]; then
+                echo "Backend Approvals: $BE_APPROVALS"
+                if [ -z "$BE_APPROVALS" ]; then
+                  echo "BE APPROVAL REQUIRED"
+                else
+                  echo "BE APPROVAL CONFIRMED"
+                  approval_status=confirmed
+                  backend_approval_required=false
+                fi
+              fi
+            else
+              echo "No approvals found"
             fi
-          else
-            echo "No approvals found"
           fi
 
           echo "exempt_team=${exempt_team}" >> $GITHUB_OUTPUT
