Clean up workflows

diff --git a/.github/workflows/ready_for_review.yml b/.github/workflows/ready_for_review.yml
--- a/.github/workflows/ready_for_review.yml
+++ b/.github/workflows/ready_for_review.yml
@@ -71,44 +71,12 @@ jobs:
           number: ${{ needs.get-pr-data.outputs.pr_number }}
           labels: ready-for-backend-review
 
-  check-backend-requirement:
-    name: Check Backend Requirement
-    needs: get-pr-data
-    if: needs.get-pr-data.outputs.pr_draft == 'false'
-    runs-on: ubuntu-latest
-    permissions: write-all
-    env:
-      pr_number: ${{ needs.get-pr-data.outputs.pr_number }}
-      pr_labels: ${{ needs.get-pr-data.outputs.pr_labels }}
-      pr_requested_teams: ${{ needs.get-pr-data.outputs.pr_requested_teams }}
-    outputs:
-      backend_approval_required: ${{ steps.check_backend_requirement.outputs.backend_approval_required }}
-    steps:
-      - name: Check Backend Requirement
-        id: check_backend_requirement
-        if: |
-          ${{ contains(fromJSON(env.pr_requested_teams), 'backend-review-group') }} ||
-          ${{ contains(fromJSON(env.pr_labels), 'require-backend-approval') }}
-        run: |
-          echo "backend_approval_required=true" >> $GITHUB_OUTPUT
-
-      - name: Add require-backend-approval label
-        uses: actions-ecosystem/action-add-labels@v1
-        if: steps.check_backend_requirement.outputs.backend_approval_required == 'true'
-        with:
-          number: ${{ env.pr_number }}
-          labels: require-backend-approval
-
-      - name: Remove require-backend-approval label
-        uses: actions-ecosystem/action-remove-labels@v1
-        if: steps.check_backend_requirement.outputs.backend_approval_required == 'false'
-        with:
-          number: ${{ env.pr_number }}
-          labels: require-backend-approval
+      - name: Fail if draft
+        run: exit 1
 
   check-workflow-status:
     name: Check Workflow Statuses
-    needs: [get-pr-data, check-backend-requirement]
+    needs: [get-pr-data]
     runs-on: ubuntu-latest
     permissions: write-all
     env:
@@ -157,10 +125,48 @@ jobs:
           number: ${{ env.pr_number }}
           labels: ready-for-backend-review
 
+      - name: Fail if workflow runs are not successfully completed
+        if: steps.check_workflow_status.outputs.failures_detected == 'true'
+        run: exit 1
+
+  check-backend-requirement:
+    name: Check Backend Requirement
+    needs: [get-pr-data, check-workflow-status]
+    if: needs.get-pr-data.outputs.pr_draft == 'false' && needs.check-workflow-status.outputs.failures_detected == 'false'
+    runs-on: ubuntu-latest
+    permissions: write-all
+    env:
+      pr_number: ${{ needs.get-pr-data.outputs.pr_number }}
+      pr_labels: ${{ needs.get-pr-data.outputs.pr_labels }}
+      pr_requested_teams: ${{ needs.get-pr-data.outputs.pr_requested_teams }}
+    outputs:
+      backend_approval_required: ${{ steps.check_backend_requirement.outputs.backend_approval_required }}
+    steps:
+      - name: Check Backend Requirement
+        id: check_backend_requirement
+        if: |
+          ${{ contains(fromJSON(env.pr_requested_teams), 'backend-review-group') }} ||
+          ${{ contains(fromJSON(env.pr_labels), 'require-backend-approval') }}
+        run: |
+          echo "backend_approval_required=true" >> $GITHUB_OUTPUT
+
+      - name: Add require-backend-approval label
+        uses: actions-ecosystem/action-add-labels@v1
+        if: steps.check_backend_requirement.outputs.backend_approval_required == 'true'
+        with:
+          number: ${{ env.pr_number }}
+          labels: require-backend-approval
+
+      - name: Remove require-backend-approval label
+        uses: actions-ecosystem/action-remove-labels@v1
+        if: steps.check_backend_requirement.outputs.backend_approval_required == 'false'
+        with:
+          number: ${{ env.pr_number }}
+          labels: require-backend-approval
+
   fetch-pr-reviews:
     name: Fetch Pull Request Reviews
     needs: [get-pr-data, check-workflow-status, check-backend-requirement]
-    # if: needs.check-workflow-status.outputs.failures_detected == 'false'
     runs-on: ubuntu-latest
     permissions: write-all
     env:
@@ -257,7 +263,6 @@ jobs:
       # The ready-for-review label will be added when pull request has not been reviewed
       - name: Add ready-for-review label
         if: |
-          needs.check-workflow-status.outputs.failures_detected == 'false' &&
           steps.verify_approval.outputs.approval_status == 'required' &&
           steps.verify_approval.outputs.team_approval_status == 'required'
         uses: actions-ecosystem/action-add-labels@v1
@@ -269,7 +274,6 @@ jobs:
       # The ready-for-backend-review label will be added for backend-review-group team members
       - name: Add ready-for-backend-review label
         if: |
-          needs.check-workflow-status.outputs.failures_detected == 'false' &&
           needs.check-backend-requirement.outputs.backend_approval_required == 'true' &&
           steps.verify_approval.outputs.approval_status == 'required' &&
           (
