revert other changes

diff --git a/.github/workflows/ready_for_review.yml b/.github/workflows/ready_for_review.yml
--- a/.github/workflows/ready_for_review.yml
+++ b/.github/workflows/ready_for_review.yml
@@ -12,16 +12,18 @@ permissions:
   id-token: write
   contents: read
 jobs:
-  fetch-pr-reviews:
-    name: Fetch Pull Request Reviews
+  get-pr-data:
+    name: Get PR Data
     runs-on: ubuntu-latest
-    permissions: write-all
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    outputs:
+      pr_number: ${{ steps.get_pr_data.outputs.pr_number }}
+      pr_draft: ${{ steps.get_pr_data.outputs.pr_draft }}
+      pr_labels: ${{ steps.get_pr_data.outputs.pr_labels }}
+      pr_requested_teams: ${{ steps.get_pr_data.outputs.pr_requested_teams }}
+      pr_branch:  ${{ steps.get_pr_data.outputs.pr_branch }}
     steps:
-      - name: Set up environment variables
-        run: |
-          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
-          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
-
       - name: Checkout PR HEAD ref
         uses: actions/checkout@v4
         with:
@@ -30,18 +32,162 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           fetch-depth: 0
 
-      - name: Get requested reviewer teams from PR payload
-        id: requested_teams
+      - name: Get pull_request data
+        id: get_pr_data
         run: |
-          echo "pr_requested_teams=$(echo '${{ toJSON(github.event.pull_request.requested_teams.*.slug) }}' | jq -c '.')" >> "$GITHUB_OUTPUT"
+          if ${{ github.event_name == 'pull_request' }}; then
+            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
+            echo "pr_draft=${{ github.event.pull_request.draft }}" >> $GITHUB_OUTPUT
+            echo "pr_labels=$(echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | jq -c '.')" >> $GITHUB_OUTPUT
+            echo "pr_requested_teams=$(echo '${{ toJSON(github.event.pull_request.requested_teams.*.name) }}' | jq -c '.')" >> $GITHUB_OUTPUT
+            echo "pr_branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
+          elif ${{ github.event_name == 'workflow_run' }}; then
+            if ${{ github.event.workflow_run.event == 'push' }}; then
+              HEAD_BRANCH="${{ github.event.workflow_run.head_branch }}"
+              echo "Workflow was triggered by push to $HEAD_BRANCH. Labeling not required."
+              exit 0
+            elif ${{ toJSON(github.event.workflow_run.pull_requests) != '[]' }}; then
+              PR_NUMBER="${{ github.event.workflow_run.pull_requests[0].number }}"
+              echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
+              echo "pr_branch=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
 
-      - name: Check if backend-review-group is requested
-        id: check_backend_requested
+              # Fetch PR details from GitHub API
+              PR_INFO=$(gh api /repos/${{ github.repository }}/pulls/${PR_NUMBER} --jq '{
+                draft: .draft,
+                labels: [.labels[].name],
+                requested_teams: [.requested_teams[].slug]
+              }')
+
+              # Extract and store individual fields
+              echo "pr_draft=$(echo "$PR_INFO" | jq -r '.draft')" >> $GITHUB_OUTPUT
+              echo "pr_labels=$(echo "$PR_INFO" | jq -c '.labels')" >> $GITHUB_OUTPUT
+              echo "pr_requested_teams=$(echo "$PR_INFO" | jq -c '.requested_teams')" >> $GITHUB_OUTPUT
+            else
+              echo "Workflow run has no associated pull requests. Labeling not performed."
+              exit 0
+            fi
+          else
+            echo "event_name: ${{ github.event_name }}"
+            echo "Pull Request not successfully retrieved."
+            exit 1
+          fi
+
+  check-workflow-status:
+    name: Check Workflow Statuses
+    needs: [get-pr-data]
+    runs-on: ubuntu-latest
+    permissions: write-all
+    env:
+      pr_number: ${{ needs.get-pr-data.outputs.pr_number }}
+      pr_branch: ${{ needs.get-pr-data.outputs.pr_branch }}
+    outputs:
+      failures_detected: ${{ steps.check_workflow_status.outputs.failures_detected }}
+    steps:
+      - name: Check if workflows have completed successfully
+        id: check_workflow_status
         run: |
-          echo "Requested teams: ${{ steps.requested_teams.outputs.pr_requested_teams }}"
-          echo '${{ steps.requested_teams.outputs.pr_requested_teams }}' | grep -q '"backend-review-group"' && \
-            echo "team_requested=true" >> "$GITHUB_OUTPUT" || \
-            echo "team_requested=false" >> "$GITHUB_OUTPUT"
+          failures=false
+          GITHUB_REPOSITORY="department-of-veterans-affairs/vets-api"
+          WORKFLOWS=("Code Checks" "Check CODEOWNERS Entries" "Audit Service Tags" "CodeQL")
+
+          for WORKFLOW in "${WORKFLOWS[@]}"; do
+            # Check if there's any in-progress run for this workflow
+            IN_PROGRESS=$(gh run list --repo "$GITHUB_REPOSITORY" --workflow="$WORKFLOW" --status=in_progress --json headBranch,event -q \
+              '.[] | select(.headBranch == "${{ env.pr_branch }}" and .event == "pull_request")')
+
+            if [ -n "$IN_PROGRESS" ]; then
+              echo "$WORKFLOW is still in progress."
+              failures=true
+            else
+              # Check if the latest completed run was successful
+              SUCCESSFUL=$(gh run list --repo "$GITHUB_REPOSITORY" --workflow="$WORKFLOW" --status=completed --json headBranch,event,conclusion -q \
+                '.[] | select(.headBranch == "${{ env.pr_branch }}" and .event == "pull_request") | select(.conclusion == "success")' | head -n 1)
+              if [ -z "$SUCCESSFUL" ]; then
+                echo "$WORKFLOW did not complete successfully."
+                failures=true
+                # break
+              else
+                echo "$WORKFLOW completed successfully."
+              fi
+            fi
+          done
+
+          echo "failures_detected=$failures" >> "$GITHUB_OUTPUT"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Remove ready-for-review label
+        if: steps.check_workflow_status.outputs.failures_detected == 'true'
+        uses: actions-ecosystem/action-remove-labels@v1
+        with:
+          number: ${{ env.pr_number }}
+          labels: ready-for-review
+
+      - name: Remove ready-for-backend-review label
+        if: steps.check_workflow_status.outputs.failures_detected == 'true'
+        uses: actions-ecosystem/action-remove-labels@v1
+        with:
+          number: ${{ env.pr_number }}
+          labels: ready-for-backend-review
+
+  check-backend-requirement:
+    name: Check Backend Requirement
+    needs: [get-pr-data, check-workflow-status]
+    runs-on: ubuntu-latest
+    permissions: write-all
+    env:
+      failures_detected:  ${{ needs.check-workflow-status.outputs.failures_detected }}
+      pr_number: ${{ needs.get-pr-data.outputs.pr_number }}
+      pr_labels: ${{ needs.get-pr-data.outputs.pr_labels }}
+      pr_requested_teams: ${{ needs.get-pr-data.outputs.pr_requested_teams }}
+    outputs:
+      backend_approval_required: ${{ steps.check_backend_requirement.outputs.backend_approval_required }}
+    steps:
+      - name: Check Backend Requirement
+        id: check_backend_requirement
+        if: |
+          ${{ contains(fromJSON(env.pr_requested_teams), 'backend-review-group') }} ||
+          ${{ contains(fromJSON(env.pr_labels), 'require-backend-approval') }}
+        run: |
+          echo "backend_approval_required=true" >> $GITHUB_OUTPUT
+
+      - name: Add require-backend-approval label
+        uses: actions-ecosystem/action-add-labels@v1
+        if: steps.check_backend_requirement.outputs.backend_approval_required == 'true'  && needs.check-workflow-status.outputs.failures_detected == 'false'
+        with:
+          number: ${{ env.pr_number }}
+          labels: require-backend-approval
+
+      - name: Remove require-backend-approval label
+        uses: actions-ecosystem/action-remove-labels@v1
+        if: steps.check_backend_requirement.outputs.backend_approval_required == 'false' && needs.check-workflow-status.outputs.failures_detected == 'false'
+        with:
+          number: ${{ env.pr_number }}
+          labels: require-backend-approval
+
+  fetch-pr-reviews:
+    name: Fetch Pull Request Reviews
+    needs: [get-pr-data, check-workflow-status, check-backend-requirement]
+    runs-on: ubuntu-latest
+    permissions: write-all
+    env:
+      backend_approval_required: ${{ needs.check-backend-requirement.outputs.backend_approval_required }}
+      failures_detected:  ${{ needs.check-workflow-status.outputs.failures_detected }}
+      pr_number: ${{ needs.get-pr-data.outputs.pr_number }}
+      pr_branch: ${{ needs.get-pr-data.outputs.pr_branch }}
+      pr_draft: ${{ needs.get-pr-data.outputs.pr_draft }}
+    outputs:
+      author_is_backend: ${{ steps.verify_approval.outputs.author_is_backend }}
+      team_approval_status: ${{ steps.verify_approval.outputs.team_approval_status }}
+      approval_status: ${{ steps.verify_approval.outputs.approval_status }}
+    steps:
+      - name: Checkout PR HEAD ref
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          fetch-depth: 0
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4.0.2
@@ -57,33 +203,100 @@ jobs:
 
       - name: Verify backend-review-group approval
         id: verify_approval
-        if: steps.check_backend_requested.outputs.team_requested == 'true'
         run: |
-          gh api /orgs/department-of-veterans-affairs/teams/backend-review-group/members --jq '.[].login' > members.txt
-          echo "Backend team members:"
-          cat members.txt
+          approval_status=required
+          team_approval_status=required
+          author_is_backend=false
+
+          BACKEND_REVIEWERS=$(gh api /orgs/department-of-veterans-affairs/teams/backend-review-group/members --jq '.[].login')
+          BACKEND_REVIEWERS=$(echo "$BACKEND_REVIEWERS" | tr '\n' '|' | sed 's/|$//')
+          echo "Backend reviewers regex: $BACKEND_REVIEWERS"
+
+          # Get PR author
+          PR_AUTHOR=$(gh pr view ${{ env.pr_number }} --json author -q '.author.login')
+          if echo "$PR_AUTHOR" | grep -qiE "^($BACKEND_REVIEWERS)$"; then
+            echo "PR author '$PR_AUTHOR' is a backend-review-group member."
+            echo "author_is_backend=true" >> "$GITHUB_OUTPUT"
+          fi
+
+          APPROVED=$(gh api /repos/${{ github.repository }}/pulls/${{ env.pr_number }}/reviews --jq '
+            [ .[]
+            | select(.state == "APPROVED" and (.dismissed_at == null))
+            ]
+            | sort_by(.submitted_at)
+            | reverse
+            | unique_by(.user.login)
+            | .[].user.login
+          ' || true)
+
+          echo "$APPROVED"
+
+          TEAM_APPROVALS=$(echo "$APPROVED" | grep -viE "^($BACKEND_REVIEWERS)$" || true)
+          echo "Team Approvals: $TEAM_APPROVALS"
+          if [ -z "$TEAM_APPROVALS" ]; then
+            echo "TEAM APPROVAL REQUIRED"
+            team_approval_status=required
+          else
+            echo "TEAM APPROVAL CONFIRMED"
+            team_approval_status=confirmed
+          fi
+
+          BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
+          echo "Backend Approvals: $BE_APPROVALS"
+          if [ -z "$BE_APPROVALS" ]; then
+            echo "BE APPROVAL REQUIRED"
+            approval_status=required
+          else
+            echo "BE APPROVAL CONFIRMED"
+            approval_status=confirmed
+          fi
+
+          echo "author_is_backend=$author_is_backend" >> "$GITHUB_OUTPUT"
+          echo "team_approval_status=$team_approval_status" >> "$GITHUB_OUTPUT"
+          echo "approval_status=$approval_status" >> "$GITHUB_OUTPUT"
         env:
           GITHUB_TOKEN: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
-      
-      - name: Check if any backend-review-group member approved the PR
-        if: steps.check_backend_requested.outputs.team_requested == 'true'
-        run: |
-          gh pr view "$PR_NUMBER" --repo "$REPO" --json reviews -q '.reviews[] | select(.state=="APPROVED") | .author.login' > approvals.txt
-          echo "Approvals by:"
-          cat approvals.txt
 
-          PASSED=false
-          while IFS= read -r member; do
-            if grep -Fxq "$member" approvals.txt; then
-              echo "✅ $member from backend-review-group has approved"
-              PASSED=true
-              break
-            fi
-          done < members.txt
+      - name: Remove ready-for-backend-review label
+        if: needs.get-pr-data.outputs.pr_draft == 'true' || needs.check-workflow-status.outputs.failures_detected == 'true'
+        uses: actions-ecosystem/action-remove-labels@v1
+        with:
+          number: ${{ needs.get-pr-data.outputs.pr_number }}
+          labels: ready-for-backend-review
 
-          if [[ "$PASSED" == "true" ]]; then
-            echo "Backend team approval satisfied."
-          else
-            echo "❌ No approvals from backend-review-group. Failing job."
-            exit 1
-          fi
+      - name: Remove ready-for-review label
+        if: needs.get-pr-data.outputs.pr_draft == 'true' || needs.check-workflow-status.outputs.failures_detected == 'true'
+        uses: actions-ecosystem/action-remove-labels@v1
+        with:
+          number: ${{ env.pr_number }}
+          labels: ready-for-review
+
+
+      - name: Fail if draft
+        if: needs.get-pr-data.outputs.pr_draft == 'true'
+        run: exit 1
+
+      # The ready-for-review label will be added when pull request has not been reviewed
+      - name: Add ready-for-review label
+        if: |
+          steps.verify_approval.outputs.approval_status == 'required' ||
+          steps.verify_approval.outputs.team_approval_status == 'required'
+        uses: actions-ecosystem/action-add-labels@v1
+        with:
+          number: ${{ env.pr_number }}
+          labels: ready-for-review
+
+      # The ready-for-backend-review label will be added when a VFS team member has reviewed the pull request
+      # The ready-for-backend-review label will be added for backend-review-group team members
+      - name: Add ready-for-backend-review label
+        if: |
+          needs.check-backend-requirement.outputs.backend_approval_required == 'true' &&
+          steps.verify_approval.outputs.approval_status == 'required' &&
+          (
+            steps.verify_approval.outputs.author_is_backend == 'true' ||
+            steps.verify_approval.outputs.team_approval_status == 'confirmed'
+          )
+        uses: actions-ecosystem/action-add-labels@v1
+        with:
+          number: ${{ env.pr_number }}
+          labels: ready-for-backend-review
