Refactor be approval

diff --git a/.github/workflows/require_be_approval.yml b/.github/workflows/require_be_approval.yml
--- a/.github/workflows/require_be_approval.yml
+++ b/.github/workflows/require_be_approval.yml
@@ -3,6 +3,8 @@ on:
   pull_request_review:
     types: [submitted]
     branches: master
+  pull_request:
+     types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, review_requested]
 permissions:
   id-token: write
   contents: read
@@ -155,50 +157,72 @@ jobs:
           ' || true)
 
           echo "Approvals: $APPROVED"
+          BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
+          TEAM_APPROVALS=$(echo "$APPROVED" | grep -viE "^($BACKEND_REVIEWERS)$" || true)
 
           for TEAM in "${EXEMPT_TEAMS[@]}"; do
-            echo "Fetching members of team: $TEAM"
-            TEAM_MEMBERS=$(gh api /orgs/department-of-veterans-affairs/teams/${TEAM}/members --paginate --jq '.[].login')
-            while IFS= read -r MEMBER; do
-              while IFS= read -r REVIEWER; do
-                if [[ -n "$MEMBER" && -n "$REVIEWER" && "$MEMBER" == "$REVIEWER" ]]; then
-                  echo "$REVIEWER is in exempt $TEAM"
-                  exempt_be_review=true
-                  break 3
-                fi
-              done <<< "$APPROVED"
-            done <<< "$TEAM_MEMBERS"
+            echo "Non BE Requested Team: $TEAM"
+            if [[ "$author_is_backend" == "false" ]]; then
+              membership_state=$(gh api -X GET \
+                "orgs/department-of-veterans-affairs/teams/${TEAM}/memberships/$PR_AUTHOR" \
+                --jq '.state' 2>/dev/null || echo "")
+              if [[ "$membership_state" == "active" ]]; then
+                echo "PR author '$PR_AUTHOR' is a member of exempt team '$TEAM'."
+                exempt_be_review=true
+                backend_approval_required=false
+                break
+              fi
+            fi
+            if [ -n "$TEAM_APPROVALS" ]; then
+              reviewer_membership_state=$(gh api -X GET \
+                "orgs/department-of-veterans-affairs/teams/${TEAM}/memberships/$APPROVED" \
+                --jq '.state' 2>/dev/null || echo "")
+             if [[ "$reviewer_membership_state" == "active" ]]; then
+                echo "PR author '$PR_AUTHOR' is a member of exempt team '$APPROVED'."
+                exempt_be_review=true
+                backend_approval_required=false
+                team_approval_status=confirmed
+                approval_status=confirmed
+                break
+              fi
+            if
           done
 
-          if [[ "${exempt_be_review}" == "true" ]]; then
-            backend_approval_required=false
-            team_approval_status=confirmed
-            approval_status=confirmed
-          elif echo "$PR_LABELS" | jq -e '. | index("exempt-be-review")' > /dev/null || \
-              echo "$PR_LABELS" | jq -e '. | index("final-review-confirmed")' > /dev/null; then
-            team_approval_status=confirmed
-            approval_status=confirmed
-            backend_approval_required=false
+          # Check PR Labels
+          PR_LABELS="${pr_labels}"
+          echo "$PR_LABELS" | jq -r '.[]' | while read -r LABEL; do
+            echo "Fetching label: $LABEL"
+            if [[ "$LABEL" == "exempt-be-review" ]]; then
+              echo "$LABEL exists"
+              exempt_be_review=true
+              backend_approval_required=false
+            fi
+            if [[ "$LABEL" == "final-review-confirmed" ]]; then
+              echo "$LABEL exists"
+              team_approval_status=confirmed
+              approval_status=confirmed
+              backend_approval_required=false
+            fi
+          done
+
+          echo "Team Approvals: $TEAM_APPROVALS"
+          if [ -z "$TEAM_APPROVALS" ]; then
+            echo "TEAM APPROVAL REQUIRED"
+            team_approval_status=required
           else
+            echo "TEAM APPROVAL CONFIRMED"
+            team_approval_status=confirmed
+          fi
+
+          if [[ "$exempt_be_review" == "false" ]]; then
             backend_approval_required=true
-            BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
             echo "Backend Approvals: $BE_APPROVALS"
             if [ -z "$BE_APPROVALS" ]; then
               echo "BE APPROVAL NOT CONFIRMED"
-              approval_status=not_confirmed
+              approval_status=required
             else
               echo "BE APPROVAL CONFIRMED"
               approval_status=confirmed
-            fi
-
-            TEAM_APPROVALS=$(echo "$APPROVED" | grep -viE "^($BACKEND_REVIEWERS)$" || true)
-            echo "Team Approvals: $TEAM_APPROVALS"
-            if [ -z "$TEAM_APPROVALS" ]; then
-              echo "TEAM APPROVAL REQUIRED"
-              team_approval_status=required
-            else
-              echo "TEAM APPROVAL CONFIRMED"
-              team_approval_status=confirmed
             fi
           fi
 
@@ -234,10 +258,6 @@ jobs:
 
       - name: Fail if draft or failures
         if: steps.verify_approval.outputs.approval_status == 'required'
-        run: exit 1
-
-      - name: Fail if backend approval not confirmed
-        if: steps.verify_approval.outputs.approval_status == 'not_confirmed'
         run: exit 1
 
       - name: Exit for non backend approvals
