require

diff --git a/.github/workflows/require_be_approval.yml b/.github/workflows/require_be_approval.yml
--- a/.github/workflows/require_be_approval.yml
+++ b/.github/workflows/require_be_approval.yml
@@ -66,6 +66,13 @@ jobs:
           number: ${{ steps.get_pr_data.outputs.pr_number }}
           labels: ready-for-backend-review
 
+      - name: Remove final-review-confirmed label
+        if: steps.pr_data.outputs.pr_draft == 'true'
+        uses: actions-ecosystem/action-remove-labels@v1
+        with:
+          number: ${{ steps.get_pr_data.outputs.pr_number }}
+          labels: final-review-confirmed
+
       - name: Fail if draft or failures
         if: steps.pr_data.outputs.pr_draft == 'true'
         run: exit 1
@@ -135,8 +142,10 @@ jobs:
       pr_draft: ${{ needs.get-pr-data.outputs.pr_draft }}
       pr_number: ${{ needs.get-pr-data.outputs.pr_number }}
       pr_branch: ${{ needs.get-pr-data.outputs.pr_branch }}
+      pr_labels: ${{ needs.get-pr-data.outputs.pr_labels }}
       failures_detected: ${{ needs.check-workflow-status.outputs.failures_detected }}
     outputs:
+      exempt_be_review: ${{ steps.verify_approval.outputs.exempt_be_review }}
       author_is_backend: ${{ steps.verify_approval.outputs.author_is_backend }}
       team_approval_status: ${{ steps.verify_approval.outputs.team_approval_status }}
       approval_status: ${{ steps.verify_approval.outputs.approval_status }}
@@ -167,9 +176,10 @@ jobs:
         run: |
           approval_status=required
           team_approval_status=required
-          echo "author_is_backend=false" >> "$GITHUB_OUTPUT"
-          echo "backend_approval_required=true" >> $GITHUB_OUTPUT
-
+          author_is_backend=false
+          backend_approval_required=true
+          exempt_be_review=false
+          PR_LABELS="${{ env.pr_labels }}"
           EXEMPT_TEAMS=(
             octo-identity
             lighthouse-dash
@@ -188,42 +198,55 @@ jobs:
           PR_AUTHOR=${{ github.event.pull_request.user.login }}
           if echo "$PR_AUTHOR" | grep -qiE "^($BACKEND_REVIEWERS)$"; then
             echo "PR author '$PR_AUTHOR' is a backend-review-group member."
-            echo "author_is_backend=true" >> "$GITHUB_OUTPUT"
+            author_is_backend=true
           fi
 
           APPROVED=$(gh api /repos/${{ github.repository }}/pulls/${{ env.pr_number }}/reviews --jq '
             [ .[]
-            | select(.state == "APPROVED" and (.dismissed_at == null))
+            | select(.state == "APPROVED")
             ]
             | sort_by(.submitted_at)
-            | reverse
-            | unique_by(.user.login)
-            | .[].user.login
+            | last
+            | .user.login
           ' || true)
 
-          echo "$APPROVED"
-          EXEMPT_REVIEW=false
+          echo "Approvals: $APPROVED"
 
-          if [ -n "$APPROVED" ]; then
-            for TEAM in "${EXEMPT_TEAMS[@]}"; do
-              echo "Fetching members of team: $TEAM"
-              TEAM_MEMBERS=$(gh api /orgs/department-of-veterans-affairs/teams/${TEAM}/members --paginate --jq '.[].login')
-              while IFS= read -r MEMBER; do
-                while IFS= read -r REVIEWER; do
-                  if [[ -n "$MEMBER" && -n "$REVIEWER" && "$MEMBER" == "$REVIEWER" ]]; then
-                    echo ""$REVIEWER" is in exempt $TEAM"
-                    EXEMPT_REVIEW=true
-                    echo "backend_approval_required=false" >> $GITHUB_OUTPUT
-                    echo "team_approval_status=confirmed" >> "$GITHUB_OUTPUT"
-                    echo "approval_status=confirmed" >> "$GITHUB_OUTPUT"
-                    exit 0
-                  fi
-                done <<< "$APPROVED"
-              done <<< "$TEAM_MEMBERS"
-            done
-          fi
+          for TEAM in "${EXEMPT_TEAMS[@]}"; do
+            echo "Fetching members of team: $TEAM"
+            TEAM_MEMBERS=$(gh api /orgs/department-of-veterans-affairs/teams/${TEAM}/members --paginate --jq '.[].login')
+            while IFS= read -r MEMBER; do
+              while IFS= read -r REVIEWER; do
+                if [[ -n "$MEMBER" && -n "$REVIEWER" && "$MEMBER" == "$REVIEWER" ]]; then
+                  echo "$REVIEWER is in exempt $TEAM"
+                  exempt_be_review=true
+                  break 3
+                fi
+              done <<< "$APPROVED"
+            done <<< "$TEAM_MEMBERS"
+          done
 
-          if [[ "$EXEMPT_REVIEW" == "false" ]]; then
+          if [[ "${exempt_be_review}" == "true" ]]; then
+            backend_approval_required=false
+            team_approval_status=confirmed
+            approval_status=confirmed
+          elif echo "$PR_LABELS" | jq -e '. | index("exempt-be-review")' > /dev/null || \
+              echo "$PR_LABELS" | jq -e '. | index("final-review-confirmed")' > /dev/null; then
+            team_approval_status=confirmed
+            approval_status=confirmed
+            backend_approval_required=false
+          else
+            backend_approval_required=true
+            BE_APPROVALS=$(echo "$APPROVED" | grep -iE ^($BACKEND_REVIEWERS)$" || true)
+            echo "Backend Approvals: $BE_APPROVALS"
+            if [ -z "$BE_APPROVALS" ]; then
+              echo "BE APPROVAL NOT CONFIRMED"
+              approval_status=not_confirmed
+            else
+              echo "BE APPROVAL CONFIRMED"
+              approval_status=confirmed
+            fi
+
             TEAM_APPROVALS=$(echo "$APPROVED" | grep -viE "^($BACKEND_REVIEWERS)$" || true)
             echo "Team Approvals: $TEAM_APPROVALS"
             if [ -z "$TEAM_APPROVALS" ]; then
@@ -233,18 +256,10 @@ jobs:
               echo "TEAM APPROVAL CONFIRMED"
               team_approval_status=confirmed
             fi
-
-            BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
-            echo "Backend Approvals: $BE_APPROVALS"
-            if [ -z "$BE_APPROVALS" ]; then
-              echo "BE APPROVAL REQUIRED"
-              approval_status=required
-            else
-              echo "BE APPROVAL CONFIRMED"
-              approval_status=confirmed
-            fi
           fi
 
+          echo "exempt_be_review=$exempt_be_review" >> "$GITHUB_OUTPUT"
+          echo "backend_approval_required=$backend_approval_required" >> "$GITHUB_OUTPUT"
           echo "team_approval_status=$team_approval_status" >> "$GITHUB_OUTPUT"
           echo "approval_status=$approval_status" >> "$GITHUB_OUTPUT"
         env:
@@ -269,9 +284,12 @@ jobs:
           number: ${{ env.pr_number }}
           labels: ready-for-backend-review
 
-      - name: Exit for non backend approvals
-        if: steps.verify_approval.outputs.backend_approval_required == 'false'
-        run: exit 0
+      - name: Add exempt-be-review label
+        if: steps.verify_approval.outputs.exempt_be_review == 'true'
+        uses: actions-ecosystem/action-add-labels@v1
+        with:
+          number: ${{ env.pr_number }}
+          labels: exempt-be-review
 
       - name: Fail if draft or failures
         if: |
@@ -279,19 +297,28 @@ jobs:
           steps.verify_approval.outputs.approval_status == 'required'
         run: exit 1
 
+      - name: Exit for non backend approvals
+        if: steps.verify_approval.outputs.backend_approval_required == 'false'
+        run: exit 0
+
       - name: Add ready-for-backend-review label
         if: |
           needs.check-workflow-status.outputs.failures_detected == 'false' &&
           steps.verify_approval.outputs.approval_status == 'required' &&
-          (
-            steps.verify_approval.outputs.team_approval_status == 'confirmed' ||
-            steps.verify_approval.outputs.author_is_backend == 'true'
-          )
+          steps.verify_approval.outputs.team_approval_status == 'confirmed'
         uses: actions-ecosystem/action-add-labels@v1
         with:
           number: ${{ env.pr_number }}
           labels: ready-for-backend-review
 
+      - name: Add final-review-confirmed label
+        if: |
+          needs.check-workflow-status.outputs.failures_detected == 'false' &&
+          steps.verify_approval.outputs.approval_status == 'confirmed'
+        uses: actions-ecosystem/action-add-labels@v1
+        with:
+          number: ${{ env.pr_number }}
+          labels: final-review-confirmed
 
       - name: Backend Approval Confirmed
         if: |
