require

diff --git a/.github/workflows/require_be_approval.yml b/.github/workflows/require_be_approval.yml
--- a/.github/workflows/require_be_approval.yml
+++ b/.github/workflows/require_be_approval.yml
@@ -161,29 +161,28 @@ jobs:
             | reverse
             | unique_by(.user.login)
             | .[].user.login
-            // true
-          ')
+          ' || true)
 
-          if [ -n "$APPROVED" ]; then
-            TEAM_APPROVALS=$(echo "$APPROVED" | grep -viE "^($BACKEND_REVIEWERS)$" || true)
-            echo "Team Approvals: $TEAM_APPROVALS"
-            if [ "$TEAM_APPROVALS" == 'true' ]; then
-              echo "TEAM APPROVAL REQUIRED"
-              team_approval_status=required
-            else
-              echo "TEAM APPROVAL CONFIRMED"
-              team_approval_status=confirmed
-            fi
+          echo "$APPROVED"
 
-            BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
-            echo "Backend Approvals: $BE_APPROVALS"
-            if [ "$BE_APPROVALS" == 'true' ]; then
-              echo "BE APPROVAL REQUIRED"
-              approval_status=required
-            else
-              echo "BE APPROVAL CONFIRMED"
-              approval_status=confirmed
-            fi
+          TEAM_APPROVALS=$(echo "$APPROVED" | grep -viE "^($BACKEND_REVIEWERS)$" || true)
+          echo "Team Approvals: $TEAM_APPROVALS"
+          if [ -z "$TEAM_APPROVALS" ]; then
+            echo "TEAM APPROVAL REQUIRED"
+            team_approval_status=required
+          else
+            echo "TEAM APPROVAL CONFIRMED"
+            team_approval_status=confirmed
+          fi
+
+          BE_APPROVALS=$(echo "$APPROVED" | grep -iE "^($BACKEND_REVIEWERS)$" || true)
+          echo "Backend Approvals: $BE_APPROVALS"
+          if [ -z "$BE_APPROVALS" ]; then
+            echo "BE APPROVAL REQUIRED"
+            approval_status=required
+          else
+            echo "BE APPROVAL CONFIRMED"
+            approval_status=confirmed
           fi
 
           echo "author_is_backend=$author_is_backend" >> "$GITHUB_OUTPUT"
